package com.tigot.rozgar.consts;

import java.text.DateFormat;
import java.text.SimpleDateFormat;

import android.net.Uri;

public interface Consts {

	String UI_SESSION_CATEGORY_NEWS_ITEM = "CATEGORY_NEWS_ITEM";
	String UI_SESSION_CATEGORY_CATEGORY_ID = "CATEGORY_CATEGORY_ID";
	String UI_SESSION_CATEGORY_MOST_OLD_NEWS = "CATEGORY_MOST_OLD_NEWS";
	String UI_SESSION_CATEGORY_SHOW_OLD = "CATEGORY_SHOW_OLD";
	String UI_SESSION_NEWS_ITEM = "NEWS_ITEM";
	String UI_SESSION_NEWS_ITEM_TAG = "itemFragmentStateTag";

	String FRAGMENT_FEED_ITEM_TAG = "feeditemTag";
	String FRAGMENT_CHANNEL_TAG = "channelTag";
	String FRAGMENT_CHANNEL_ID = "channelId";

	String PREF_CHANNEL_INDEX = "CHANNEL_INDEX";
	String PREF_REFRESH_PERIOD = "REFRESH_PERIOD";
	Integer PREF_REFRESH_PERIOD_DEFAULT = 4 * 60 * 1000;
	String PREF_LAST_CLEARING_DATE = "LAST_CLEARING_DATE";
	Long PREF_LAST_CLEARING_DATE_PERIOD = (long) (12 * 60 * 60 * 1000);

	String INTENT_ACTIVITY_FEEDITEM = "ACTIVITY_FEEDITEM_ID";
	String INTENT_DOWNLOAD_CATEGORY_ID = "DOWNLOAD_CHANNEL_ID";
	String INTENT_DOWNLOAD_CALLBACK_ACTION = "DOWNLOAD_CALLBACK_ACTION";
	String INTENT_DOWNLOAD_BEFORE = "DOWNLOAD_BEFORE";
	String INTENT_NEWSITEM_NEWSITEM_ID = "NEWSITEM_NEWSITEM_ID";
	String INTENT_NEWSITEM_CATEGORY_ID = "NEWSITEM_CATEGORY_ID";
	String INTENT_NEWSITEM_CATEGORY_TITLE = "NEWSITEM_CATEGORY_TITLE";
	String INTENT_NEWSITEM_CATEGORY_SHOW_OLD = "NEWSITEM_CATEGORY_SHOW_OLD";
	String INTENT_NEWSITEM_POSITION = "NEWSITEM_POSITION";
	String INTENT_DOWNLOADED_CATEGORY_ID = "DOWNLOADED_CATEGORY_ID";

	String BUNDLE_TOP_CATEGORY_LIST = "TOP_CATEGORY_LIST";
	
	String RECEIVER_ACTION_RELOAD_CATEGORY_UI = "RELOAD_UI";
	String RECEIVER_ACTION_RELOAD_TOP_UI = "RELOAD_TOP_UI";
	String RECEIVER_ACTION_RELOAD_CATEGORY_IMAGES = "RELOAD_CATEGORY_IMAGES";

	String CATEGORY_DEFAULT = "اخبار";
	Long CLEARING_DATE_PERIOD = (long) (7 * 24 * 60 * 60 * 1000);
	Integer CATEGORY_DEFAULT_CATEGORY_ID = 1;
	DateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	String TOP_CATEGORIES_LIST = "1,2,3";
	String TOP_CATEGORIES_CUSTOM_ORDER = "CASE CATEGORY_ID WHEN %s THEN 0 WHEN %s THEN 1 WHEN %s THEN 2 END";
	Integer ARTICLE_WIDTH_DP = 300;
	
	String URL_ALL_CATEGORIES = "http://dari.rozgar.eu/GetJSONArticles.php";
	// http://dari.rozgar.eu/GetArticlesByCategory.php?categoryId=4&created=2014-11-11 13:06:00
	String URL_CATEGORY = "http://dari.rozgar.eu/GetArticlesByCategory.php?categoryId=%s&created=%s";
	String URL_NEWSITEM_IMAGE_PREFIX = "http://rozgar.eu/subdomain/dari/files/";
	String URL_CATEGORY_IMAGES = "http://dari.rozgar.eu/GetCategoryImagesFromCategories.php";
	String URL_CATEGORY_IMAGE_PREFIX = "http://rozgar.eu/subdomain/dari/files/"; //Category_img/
	
	// ****************** database *****************
	
	String AUTHORITY = "com.tigot.rozgarprovider";
    String CONTENT_TYPE_CATEGORY = "content://" + AUTHORITY + ".data.category";
    String CONTENT_TYPE_NEWSITEM = "content://" + AUTHORITY + ".data.newsitem";
	Uri CONTENT_CATEGORY_URI = Uri.parse("content://" + AUTHORITY + "/CATEGORY");
	Uri CONTENT_NEWSITEM_URI = Uri.parse("content://" + AUTHORITY + "/NEWSITEM");

	String DB_COLUMN_ID = "_id";
    int COLUMN_INDEX_ID = 0;
	
	String DB_COLUMN_CATEGORY_ID = "CATEGORY_ID";
	String DB_COLUMN_CATEGORY_TITLE = "TITLE";
	String DB_COLUMN_CATEGORY_IMAGE = "IMAGE";
	String DB_COLUMN_CATEGORY_LAST_DOWNLOADED = "LAST_DOWNLOADED";
    int COLUMN_INDEX_CATEGORY_ID = 1;
    int COLUMN_INDEX_CATEGORY_TITLE = 2;
    int COLUMN_INDEX_CATEGORY_IMAGE = 3;
    int COLUMN_INDEX_CATEGORY_LAST_DOWNLOADED = 4;
	
	String DB_COLUMN_NEWSITEM_TITLE = "TITLE";
	String DB_COLUMN_NEWSITEM_AUTHOR = "AUTHOR";
	String DB_COLUMN_NEWSITEM_CATEGORY_ID = "CHANNEL_ID";
	String DB_COLUMN_NEWSITEM_ARTICLE_IMAGE = "ARTICLE_IMAGE";
//	String DB_COLUMN_NEWSITEM_ARTICLE_IMAGE_MD5 = "ARTICLE_IMAGE_MD5";
	String DB_COLUMN_NEWSITEM_CREATED = "CREATED";
	String DB_COLUMN_NEWSITEM_ABSTRACT_TITLE = "ABSTRACT_TITLE";
	String DB_COLUMN_NEWSITEM_CAPTION_IMAGE = "CAPTION_IMAGE";
//	String DB_COLUMN_NEWSITEM_CAPTION_IMAGE_MD5 = "CAPTION_IMAGE_MD5";
	String DB_COLUMN_NEWSITEM_BODY = "BODY";
	String DB_COLUMN_NEWSITEM_ID_MD5 = "ID_MD5";
    int COLUMN_INDEX_NEWSITEM_TITLE = 1;
    int COLUMN_INDEX_NEWSITEM_AUTHOR = 2;
    int COLUMN_INDEX_NEWSITEM_CATEGORY_ID = 3;
    int COLUMN_INDEX_NEWSITEM_ARTICLE_IMAGE = 4;
//    int COLUMN_INDEX_NEWSITEM_ARTICLE_IMAGE_MD5 = 5;
    int COLUMN_INDEX_NEWSITEM_CREATED = 5;
    int COLUMN_INDEX_NEWSITEM_ABSTRACT_TITLE = 6;
    int COLUMN_INDEX_NEWSITEM_CAPTION_IMAGE = 7;
//    int COLUMN_INDEX_NEWSITEM_CAPTION_IMAGE_MD5 = 9;
    int COLUMN_INDEX_NEWSITEM_BODY = 8;
    int COLUMN_INDEX_NEWSITEM_ID_MD5 = 9;

    String[] PROJECTION_CATEGORIES = new String[] { DB_COLUMN_ID, // 0
    		DB_COLUMN_CATEGORY_ID, // 1
    		DB_COLUMN_CATEGORY_TITLE, // 2
    		DB_COLUMN_CATEGORY_IMAGE, // 3
    		DB_COLUMN_CATEGORY_LAST_DOWNLOADED, // 4
	};
    String[] PROJECTION_NEWSITEMS = new String[] { DB_COLUMN_ID, // 0
    		DB_COLUMN_NEWSITEM_TITLE, // 1
    		DB_COLUMN_NEWSITEM_AUTHOR, // 2
    		DB_COLUMN_NEWSITEM_CATEGORY_ID, // 3
    		DB_COLUMN_NEWSITEM_ARTICLE_IMAGE, // 4
//    		DB_COLUMN_NEWSITEM_ARTICLE_IMAGE_MD5, // 5
    		DB_COLUMN_NEWSITEM_CREATED, // 5
    		DB_COLUMN_NEWSITEM_ABSTRACT_TITLE, // 6
    		DB_COLUMN_NEWSITEM_CAPTION_IMAGE, // 7
//    		DB_COLUMN_NEWSITEM_CAPTION_IMAGE_MD5, // 8
    		DB_COLUMN_NEWSITEM_BODY, // 8
    		DB_COLUMN_NEWSITEM_ID_MD5, // 9
	};
	
}
